Feature: "tricorder init:githook" installs the Git pre-commit hook

  Scenario: install the pre-commit hook into a Git repository
    Given a Git repository
    When executing "tricorder init:githook"
    Then it prints
      """
      installed .git/hooks/pre-commit

      I have created the Git pre-commit hook at .git/hooks/pre-commit.

      From now on, Tricorder automatically formats all code that gets committed.
      """
    And it prints nothing to STDERR
    And the exit code is 0
    And file ".git/hooks/pre-commit" now matches
      """
      (?s)\A#!/bin/sh\n\n# Generated by `tricorder init:githook`.\n# Safe to edit.\n# Run "tricorder init:githook --force" to reset.\n\nTRICORDER="[^"]+"\n\[ -x "\$TRICORDER" \] \|\| exit 0\n"\$TRICORDER" precommit\z
      """
    And file ".git/hooks/pre-commit" now matches
      """
      target/release/tricorder
      """
    And file ".git/hooks/pre-commit" is executable

  Scenario: not a Git repository
    When executing "tricorder init:githook"
    Then it prints
      """
      not a git repository (no .git directory)
      """
    And the exit code is 1

  Scenario: Git worktree
    Given a file ".git" with content
      """
      gitdir: /tmp/somewhere
      """
    When executing "tricorder init:githook"
    Then it prints
      """
      please run this command in the main Git worktree
      """
    And the exit code is 1

  Scenario: existing hook is left unchanged
    Given a Git repository
    And a file ".git/hooks/pre-commit" with content
      """
      existing hook
      """
    When executing "tricorder init:githook"
    Then it prints
      """
      skipped .git/hooks/pre-commit (exists; pass --force to overwrite)
      Could not install the Git pre-commit hook because it already exists.
      To install anyway, run "tricorder init:githook --force".
      """
    And it prints nothing to STDERR
    And the exit code is 1
    And file ".git/hooks/pre-commit" is unchanged

  @this
  Scenario: --force overwrites an existing hook
    Given a Git repository
    And a file ".git/hooks/pre-commit" with content
      """
      existing hook
      """
    When executing "tricorder init:githook --force"
    Then it prints
      """
      installed .git/hooks/pre-commit

      I have created the Git pre-commit hook at .git/hooks/pre-commit.

      From now on, Tricorder automatically formats all code that gets committed.
      """
    And it prints nothing to STDERR
    And the exit code is 0
    And file ".git/hooks/pre-commit" now matches
      """
      target/release/tricorder
      """
    And file ".git/hooks/pre-commit" is executable
