Feature: "tricorder init:claude" installs Claude-compatible agent hooks

  Scenario: install hooks into an empty project
    When executing "tricorder init:claude"
    Then it prints
      """
      installed .claude/settings.json
      installed .claude/tricorder-hooks/post_write.sh

      Your Claude-compatible coding agent now runs all linters after every Write/Edit.
      """
    And it prints nothing to STDERR
    And the exit code is 0
    And file ".claude/settings.json" now has content
      """
      {
        "hooks": {
          "PostToolUse": [
            {
              "matcher": "Write|Edit|MultiEdit",
              "hooks": [
                {
                  "type": "command",
                  "command": ".claude/tricorder-hooks/post_write.sh",
                  "statusMessage": "Tricorder: running linters...",
                  "timeout": 120
                }
              ]
            }
          ]
        }
      }
      """
    And file ".claude/tricorder-hooks/post_write.sh" now matches these lines
      """
      #!/bin/sh

      # Generated by "tricorder init:claude".
      # Safe to edit.
      # Re-run "tricorder init:claude --force" to reset.

      TRICORDER=".*/tricorder"
      [ -x "$TRICORDER" ] || exit 0
      "$TRICORDER" lint
      """
    And file ".claude/tricorder-hooks/post_write.sh" is executable

  Scenario: claude settings exist already
    Given a file ".claude/settings.json" with content
      """
      existing settings
      """
    When executing "tricorder init:claude"
    Then it prints
      """
        I did not install the Claude hooks because these files already exist:
          .claude/settings.json

        To install anyway, please re-run with the "--force" flag.
      """
    And it prints nothing to STDERR
    And the exit code is 1
    And file ".claude/settings.json" is unchanged
    And file ".claude/tricorder-hooks/post_write.sh" does not exist

  Scenario: claude hook exists already
    And a file ".claude/tricorder-hooks/post_write.sh" with content
      """
      existing hook
      """
    When executing "tricorder init:claude"
    Then it prints
      """
        I did not install the Claude hooks because these files already exist:
          .claude/tricorder-hooks/post_write.sh

        To install anyway, please re-run with the "--force" flag.
      """
    And it prints nothing to STDERR
    And the exit code is 1
    And file ".claude/settings.json" does not exist
    And file ".claude/tricorder-hooks/post_write.sh" is unchanged

  Scenario: --force overwrites existing files
    Given a file ".claude/settings.json" with content
      """
      existing settings
      """
    And a file ".claude/tricorder-hooks/post_write.sh" with content
      """
      existing hook
      """
    When executing "tricorder init:claude --force"
    Then it prints
      """
      installed .claude/settings.json
      installed .claude/tricorder-hooks/post_write.sh

      Your Claude-compatible coding agent now runs all linters after every Write/Edit.
      """
    And it prints nothing to STDERR
    And the exit code is 0
    And file ".claude/settings.json" now has content
      """
      {
        "hooks": {
          "PostToolUse": [
            {
              "matcher": "Write|Edit|MultiEdit",
              "hooks": [
                {
                  "type": "command",
                  "command": ".claude/tricorder-hooks/post_write.sh",
                  "statusMessage": "Tricorder: running linters...",
                  "timeout": 120
                }
              ]
            }
          ]
        }
      }
      """
    And file ".claude/tricorder-hooks/post_write.sh" now matches these lines
      """
      #!/bin/sh

      # Generated by "tricorder init:claude".
      # Safe to edit.
      # Re-run "tricorder init:claude --force" to reset.

      TRICORDER=".*/tricorder"
      [ -x "$TRICORDER" ] || exit 0
      "$TRICORDER" lint
      """
    And file ".claude/tricorder-hooks/post_write.sh" is executable
