Feature: "trident init:claude" installs Claude-compatible agent hooks

@this
  Scenario: install hooks into an empty project
    When executing "trident init:claude"
    Then it prints
      """
      created .claude/settings.json
      created .claude/trident-hooks/post_write.sh

      Your Claude-compatible coding agent now runs all linters after every Write/Edit.
      """
    And it prints nothing to STDERR
    And the exit code is 0
    And file ".claude/settings.json" now has content
      """
      {
        "hooks": {
          "PostToolUse": [
            {
              "matcher": "Write|Edit|MultiEdit",
              "hooks": [
                {
                  "type": "command",
                  "command": ".claude/trident-hooks/post_write.sh",
                  "statusMessage": "Trident: running linters...",
                  "timeout": 120
                }
              ]
            }
          ]
        }
      }
      """
    And file ".claude/trident-hooks/post_write.sh" now matches these lines
      """
      #!/bin/sh

      # Generated by "trident init:claude".
      # Safe to edit.
      # Re-run "trident init:claude --force" to reset.

      TRIDENT=".*\btrident(\.exe)?"
      [ -x "$TRIDENT" ] || exit 0
      "$TRIDENT" postedit
      """
    And file ".claude/trident-hooks/post_write.sh" is executable

  Scenario: claude settings exist already
    Given a file ".claude/settings.json" with content
      """
      existing settings
      """
    When executing "trident init:claude"
    Then it prints
      """
      I did not install the Claude hooks because these files already exist:
        .claude/settings.json

      To install anyway, please re-run with the "--force" flag.
      """
    And it prints nothing to STDERR
    And the exit code is 1
    And file ".claude/settings.json" is unchanged
    And file ".claude/trident-hooks/post_write.sh" does not exist

  Scenario: claude hook exists already
    And a file ".claude/trident-hooks/post_write.sh" with content
      """
      existing hook
      """
    When executing "trident init:claude"
    Then it prints
      """
      I did not install the Claude hooks because these files already exist:
        .claude/trident-hooks/post_write.sh

      To install anyway, please re-run with the "--force" flag.
      """
    And it prints nothing to STDERR
    And the exit code is 1
    And file ".claude/settings.json" does not exist
    And file ".claude/trident-hooks/post_write.sh" is unchanged

  Scenario: --force overwrites existing files
    Given a file ".claude/settings.json" with content
      """
      existing settings
      """
    And a file ".claude/trident-hooks/post_write.sh" with content
      """
      existing hook
      """
    When executing "trident init:claude --force"
    Then it prints
      """
      created .claude/settings.json
      created .claude/trident-hooks/post_write.sh

      Your Claude-compatible coding agent now runs all linters after every Write/Edit.
      """
    And it prints nothing to STDERR
    And the exit code is 0
    And file ".claude/settings.json" now has content
      """
      {
        "hooks": {
          "PostToolUse": [
            {
              "matcher": "Write|Edit|MultiEdit",
              "hooks": [
                {
                  "type": "command",
                  "command": ".claude/trident-hooks/post_write.sh",
                  "statusMessage": "Trident: running linters...",
                  "timeout": 120
                }
              ]
            }
          ]
        }
      }
      """
    And file ".claude/trident-hooks/post_write.sh" now matches these lines
      """
      #!/bin/sh

      # Generated by "trident init:claude".
      # Safe to edit.
      # Re-run "trident init:claude --force" to reset.

      TRIDENT=".*\btrident(\.exe)?"
      [ -x "$TRIDENT" ] || exit 0
      "$TRIDENT" postedit
      """
    And file ".claude/trident-hooks/post_write.sh" is executable
