Feature: "trident init:githook" installs the Git pre-commit hook

  Scenario: install the pre-commit hook into an empty Git repository
    Given a Git repository
    When executing "trident init:githook"
    Then it prints
      """
      created .git/hooks/pre-commit

      From now on, Trident automatically formats all code that gets committed.
      """
    And it prints nothing to STDERR
    And the exit code is 0
    And file ".git/hooks/pre-commit" now matches these lines
      """
      #!/bin/sh

      # Generated by `trident init:githook`.
      # Safe to edit.
      # Run "trident init:githook --force" to reset.

      TRIDENT=".*/trident"
      [ -x "$TRIDENT" ] || exit 0
      "$TRIDENT" precommit
      """
    And file ".git/hooks/pre-commit" is executable

  Scenario: not a Git repository
    When executing "trident init:githook"
    Then it prints
      """
      not a git repository (no .git directory)
      """
    And the exit code is 1

  Scenario: Git worktree
    Given a file ".git" with content
      """
      gitdir: /tmp/somewhere
      """
    When executing "trident init:githook"
    Then it prints
      """
      please run this command in the main Git worktree
      """
    And the exit code is 1

  Scenario: existing hook is left unchanged
    Given a Git repository
    And a file ".git/hooks/pre-commit" with content
      """
      existing hook
      """
    When executing "trident init:githook"
    Then it prints
      """
      I did not install the Git pre-commit hook because these files already exist:
        .git/hooks/pre-commit

      To install anyway, please re-run with the "--force" flag.
      """
    And it prints nothing to STDERR
    And the exit code is 1
    And file ".git/hooks/pre-commit" is unchanged

  Scenario: --force overwrites an existing hook
    Given a Git repository
    And a file ".git/hooks/pre-commit" with content
      """
      existing hook
      """
    When executing "trident init:githook --force"
    Then it prints
      """
      created .git/hooks/pre-commit

      From now on, Trident automatically formats all code that gets committed.
      """
    And it prints nothing to STDERR
    And the exit code is 0
    And file ".git/hooks/pre-commit" now matches these lines
      """
      #!/bin/sh

      # Generated by `trident init:githook`.
      # Safe to edit.
      # Run "trident init:githook --force" to reset.

      TRIDENT=".*/trident"
      [ -x "$TRIDENT" ] || exit 0
      "$TRIDENT" precommit
      """
    And file ".git/hooks/pre-commit" is executable
