#!/usr/bin/env bash
# Generated by `tricorder init`. Safe to edit; re-run init --force to reset.
#
# PostToolUse hook for Claude Code and Code Puppy. Runs after every
# Write/Edit/MultiEdit; exits 2 with the findings on stderr if anything
# is unclean so the agent self-corrects. No-ops silently when tricorder
# is not installed.

set -euo pipefail
command -v tricorder >/dev/null 2>&1 || exit 0

output=$(tricorder check 2>&1)
ec=$?
[ $ec -eq 0 ] && exit 0

{
    printf '%s\n' "$output"
    echo "---"
    echo "Tricorder reported issues above. Fix them before proceeding."
} >&2
exit 2
