#!/usr/bin/env bash
# Generated by `tricorder init`. Safe to edit; re-run init --force to reset.
#
# PreToolUse hook for Claude Code and Code Puppy. Reads the agent's
# tool-call JSON on stdin; only acts when the command being run is
# `git commit ...`, in which case it runs tricorder and blocks the
# commit (exit 2) if anything is unclean.

set -euo pipefail
command -v tricorder >/dev/null 2>&1 || exit 0

tool_input=$(cat || echo '{}')

# Best-effort parse without depending on jq: pull the .tool_input.command
# string. Falls back to running tricorder if parsing fails, which is the
# safer default for a pre-commit gate.
cmd=$(printf '%s' "$tool_input" \
    | python3 -c 'import json,sys; print(json.loads(sys.stdin.read()).get("tool_input",{}).get("command",""))' \
    2>/dev/null || echo "")

[[ "$cmd" == git\ commit* ]] || exit 0

output=$(tricorder check 2>&1)
ec=$?
[ $ec -eq 0 ] && exit 0

{
    printf '%s\n' "$output"
    echo "---"
    echo "Tricorder reported issues above; commit blocked. Fix and retry."
} >&2
exit 2
